name: cinereview
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  flutter_phosphor_icons: ^0.0.1+6
  cloud_firestore: ^4.8.4
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - .env
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
